apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-frontend
 namespace: ljh-dev
spec:
 selector:
   matchLabels:
    type: web
 replicas: 1
 template:
   metadata:
     labels:
       type: web
   spec:
    containers:
    - name: container
      image: front:latest
      envFrom:
      - configMapRef:
          name: frontend-cm
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m