apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: ljh-dev
  labels:
    type: frontend
spec:
  containers:
  - name: container
    image: gugucone/front:1.2
    command: ["/bin/sh", "-ec", "envsubst '$BACKEND_SVC_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    envFrom:
    - configMapRef:
        name: frontend-cm